[project]
name = "ds295r"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hayden Case", email = "haymonkey04@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ds295r = "ds295r:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
